# Generated by Django 3.2 on 2023-06-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('solution provider', 'Solution Provider'), ('solution seeker', 'Solution Seeker')], max_length=50, null=True),
        ),
    ]
